### ISSUE TITLE
java.util.ServiceConfigurationError: org.testng.ITestNGListener: Provider io.qameta.allure.testng.AllureTestNg could not be instantiated

### ISSUE THREAD

**Issue by AjitSingh12** [allure-examples/allure-gradle-testng-example#5]
I have got a issue in gradle project 
dependencies are used that file attached
[buildgradle.txt](https://github.com/allure-examples/allure-gradle-testng-example/files/2781533/buildgradle.txt)

"C:\Program Files\Java\jdk1.8.0_77\bin\java.exe" 

**java.util.ServiceConfigurationError: org.testng.ITestNGListener: Provider io.qameta.allure.testng.AllureTestNg could not be instantiated**
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:967)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:906)
	at org.testng.TestNG.initializeEverything(TestNG.java:996)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/Versioned
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.qameta.allure.FileSystemResultsWriter.<init>(FileSystemResultsWriter.java:27)
	at io.qameta.allure.AllureLifecycle.getDefaultWriter(AllureLifecycle.java:281)
	at io.qameta.allure.AllureLifecycle.<init>(AllureLifecycle.java:47)
	at io.qameta.allure.Allure.getLifecycle(Allure.java:30)
	at io.qameta.allure.testng.AllureTestNg.<init>(AllureTestNg.java:119)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.Versioned
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more

Process finished with exit code -1

**Comment by baev** [comment]
You are using old testng adaptor `allure-testng-adaptor` together with a new one `allure-testng`

Please follow the steps described in documentation https://docs.qameta.io/allure/#_testng 
For questions you can also use our Gitter chat https://gitter.im/allure-framework/allure-core

**Comment by AjitSingh12** [comment]
compile group: 'ru.yandex.qatools.allure', name: 'allure-testng-adaptor', version: '1.5.4'

i am using above latest version .

**Comment by baev** [comment]
Since version 2.0 artefact coordinates was changed to `io.qameta.allrue:allure-testng`

**Comment by AjitSingh12** [comment]
compile 'org.seleniumhq.selenium:selenium-api:3.11.0'
    compile 'org.seleniumhq.selenium:selenium-java:3.10.0'
    compile 'org.apache.poi:poi:3.17'
    compile 'org.apache.poi:poi-ooxml:3.17'
    compile 'com.itextpdf:itextpdf:5.5.13'
    compile 'io.qameta.allure:allure-java-commons:2.7.0'
    compile 'io.qameta.allure:allure2-model-api:1.0-BETA6'
    compile group: 'io.qameta.allure', name: 'allure-plugin-api', version: '2.0.1'
    compile group: 'io.qameta.allure', name: 'allure-testng', version: '2.9.0'
    compile group: 'ru.yandex.qatools.allure', name: 'allure-junit-adaptor', version: '1.5.4'
    compile group: 'org.mockito', name: 'mockito-all', version: '1.10.19'
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'ru.yandex.qatools.allure', name: 'allure-testng-adaptor', version: '1.5.4'
    testCompile group: 'org.testng', name: 'testng', version: '6.7'
    compile group: 'commons-io', name: 'commons-io', version: '2.4'
    compile group: 'org.aspectj', name: 'aspectjweaver', version: '1.9.1'
    compile group: 'ru.yandex.qatools.allure', name: 'allure-cli', version: '1.3.5'
    compile group: 'org.apache.pdfbox', name: 'pdfbox', version: '1.8.2' 


this is all dependencies that i am using now.

**Comment by baev** [comment]
as I said before you have many wrong dependencies: 

```
compile 'io.qameta.allure:allure-java-commons:2.7.0'
compile 'io.qameta.allure:allure2-model-api:1.0-BETA6'
compile group: 'io.qameta.allure', name: 'allure-plugin-api', version: '2.0.1'
compile group: 'ru.yandex.qatools.allure', name: 'allure-junit-adaptor', version: '1.5.4'
compile group: 'ru.yandex.qatools.allure', name: 'allure-testng-adaptor', version: '1.5.4'
compile group: 'ru.yandex.qatools.allure', name: 'allure-cli', version: '1.3.5'
```

should be removed. Please follow the steps described in docs to configure Allure proper way
